CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  price DECIMAL(12, 2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO products (name, price)
SELECT *
FROM (
  SELECT 'Product Demo A' AS name, 125000.00 AS price
  UNION ALL SELECT 'Product Demo B', 250000.00
  UNION ALL SELECT 'Product Demo C', 375000.00
) AS seed
WHERE NOT EXISTS (SELECT 1 FROM products);
